version: '2'
services:
    candidate-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/candidate/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=candidate
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
